import React, { useState } from 'react';
import { Cpu, HardDrive, Layers, Server, Zap, CheckCircle2 } from 'lucide-react';

interface HardwareBenchmark {
  machine: string;
  year: number;
  cpu: string;
  clockMhz: number;
  busWidth: string;
  fpsCapability: string;
  status: 'functional' | 'optimal' | 'enthusiast';
  notes: string;
}

const BENCHMARKS: HardwareBenchmark[] = [
  {
    machine: 'IBM PC/XT 5160',
    year: 1983,
    cpu: 'Intel 8088',
    clockMhz: 4.77,
    busWidth: '8-bit external / 16-bit internal',
    fpsCapability: '~14 - 18 FPS',
    status: 'functional',
    notes: 'Requires 8-bit ISA VGA card (e.g. Oak OTI-067 or Trident 8900). 2BPP bitplane decoding creates heavy bus bottleneck.',
  },
  {
    machine: 'IBM PC/AT 5170',
    year: 1984,
    cpu: 'Intel 80286',
    clockMhz: 12.0,
    busWidth: '16-bit ISA bus',
    fpsCapability: '~60 FPS (V-Sync locked)',
    status: 'optimal',
    notes: 'Ideal vintage sweet spot. 16-bit word moves via REP MOVSW allow smooth 60-70Hz animation locked to vertical retrace.',
  },
  {
    machine: 'Compaq Deskpro 386',
    year: 1986,
    cpu: 'Intel 80386DX',
    clockMhz: 33.0,
    busWidth: '32-bit architecture',
    fpsCapability: '350+ FPS unthrottled',
    status: 'optimal',
    notes: 'Flawless execution. Real-mode instructions execute with low clock cycles; vertical sync polling prevents tearing.',
  },
  {
    machine: 'Gateway 2000 486DX2',
    year: 1992,
    cpu: 'Intel 80486DX2',
    clockMhz: 66.0,
    busWidth: '32-bit VLB / PCI',
    fpsCapability: '1,400+ FPS',
    status: 'enthusiast',
    notes: '8KB L1 cache and fast VESA Local Bus (VLB) VGA makes framebuffer writes almost instantaneous (<1ms/frame).',
  },
  {
    machine: 'DOSBox / FreeDOS / VirtualBox',
    year: 2026,
    cpu: 'Modern x86-64 Emulation',
    clockMhz: 3000.0,
    busWidth: 'Emulated 16-bit Real Mode',
    fpsCapability: '100% Cycle Accurate',
    status: 'optimal',
    notes: 'Standard DOS gaming emulation standard. The built-in MZ executable generated by GB2DOS runs out-of-the-box.',
  },
];

export const HardwareSpecsView: React.FC = () => {
  const [selectedMachine, setSelectedMachine] = useState<HardwareBenchmark>(BENCHMARKS[1]);

  return (
    <div className="space-y-6">
      {/* Title */}
      <div className="p-4 bg-neutral-900 border border-neutral-800 rounded-lg flex flex-wrap items-center justify-between gap-4">
        <div className="space-y-1">
          <div className="flex items-center gap-2">
            <span className="font-pixel text-xl text-amber-400">
              LEGACY x86 HARDWARE ARCHITECTURE &amp; COMPATIBILITY
            </span>
            <span className="text-xs font-mono px-2 py-0.5 rounded bg-amber-400/10 text-amber-300 border border-amber-400/30">
              Real-Mode 16-Bit · Segment:Offset Addressing · 640KB Conventional Memory
            </span>
          </div>
          <p className="text-xs text-neutral-400 max-w-3xl">
            Detailed hardware analysis of executing Game Boy 2BPP graphics and converted SM83 code on historic IBM PC/XT, AT 286, 386, and 486 computers running MS-DOS with VGA adapters.
          </p>
        </div>
      </div>

      {/* Hardware Benchmark Table */}
      <div className="bg-neutral-900 border border-neutral-800 rounded-lg overflow-hidden">
        <div className="px-4 py-3 border-b border-neutral-800 flex items-center justify-between">
          <span className="text-xs font-semibold text-neutral-200 tracking-wide font-mono flex items-center gap-2">
            <Server size={14} className="text-amber-400" />
            VINTAGE HARDWARE PLATFORM COMPATIBILITY MATRIX
          </span>
          <span className="text-[11px] font-mono text-neutral-400">
            5 Historic Generations
          </span>
        </div>

        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs font-mono">
            <thead className="bg-neutral-950 text-neutral-400 border-b border-neutral-800">
              <tr>
                <th className="px-4 py-3 font-semibold">Platform &amp; Year</th>
                <th className="px-4 py-3 font-semibold">Processor &amp; Clock</th>
                <th className="px-4 py-3 font-semibold">Bus Architecture</th>
                <th className="px-4 py-3 font-semibold">Estimated Frame Rate</th>
                <th className="px-4 py-3 font-semibold">Status</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-neutral-800/60">
              {BENCHMARKS.map((bench) => {
                const isSelected = selectedMachine.machine === bench.machine;
                return (
                  <tr
                    key={bench.machine}
                    onClick={() => setSelectedMachine(bench)}
                    className={`cursor-pointer transition-colors ${
                      isSelected
                        ? 'bg-amber-500/10'
                        : 'hover:bg-neutral-800/40'
                    }`}
                  >
                    <td className="px-4 py-3">
                      <span className="font-semibold text-neutral-200 block">
                        {bench.machine}
                      </span>
                      <span className="text-[10px] text-neutral-500">{bench.year}</span>
                    </td>
                    <td className="px-4 py-3">
                      <span className="text-amber-300 block">{bench.cpu}</span>
                      <span className="text-[10px] text-neutral-400 tabular-nums">
                        {bench.clockMhz} MHz
                      </span>
                    </td>
                    <td className="px-4 py-3 text-neutral-300">{bench.busWidth}</td>
                    <td className="px-4 py-3 text-emerald-400 font-semibold tabular-nums">
                      {bench.fpsCapability}
                    </td>
                    <td className="px-4 py-3">
                      <span
                        className={`inline-flex items-center gap-1 px-2 py-0.5 rounded text-[11px] font-medium ${
                          bench.status === 'optimal'
                            ? 'bg-emerald-500/10 text-emerald-400 border border-emerald-500/30'
                            : bench.status === 'enthusiast'
                            ? 'bg-cyan-500/10 text-cyan-300 border border-cyan-500/30'
                            : 'bg-amber-500/10 text-amber-300 border border-amber-500/30'
                        }`}
                      >
                        <CheckCircle2 size={11} />
                        {bench.status === 'optimal'
                          ? 'Optimal (60Hz)'
                          : bench.status === 'enthusiast'
                          ? 'Ultra Fast'
                          : 'Compatible'}
                      </span>
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>

        {/* Selected platform notes */}
        <div className="p-4 bg-neutral-950 border-t border-neutral-800 text-xs font-mono flex items-start gap-3">
          <div className="p-2 rounded bg-neutral-900 border border-neutral-800 text-amber-400 shrink-0">
            <Zap size={16} />
          </div>
          <div className="space-y-1">
            <span className="text-neutral-300 font-semibold">
              Deployment Notes for {selectedMachine.machine} ({selectedMachine.cpu}):
            </span>
            <p className="text-neutral-400 leading-relaxed font-sans text-xs">
              {selectedMachine.notes}
            </p>
          </div>
        </div>
      </div>

      {/* Real Mode Segment Arithmetic & Memory Map */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Segment:Offset Arithmetic Card */}
        <div className="p-5 bg-neutral-900 border border-neutral-800 rounded-lg space-y-4">
          <div className="flex items-center gap-2 border-b border-neutral-800 pb-3">
            <Cpu size={16} className="text-amber-400" />
            <span className="text-xs font-semibold text-neutral-200 tracking-wide font-mono">
              REAL MODE 20-BIT ADDRESSING ARITHMETIC
            </span>
          </div>

          <p className="text-xs text-neutral-300 font-sans leading-relaxed">
            In Real Mode, the 8086 CPU uses 16-bit segment registers and 16-bit offset registers to access up to 1 MB (<code className="text-amber-300 font-mono">2^20 bytes</code>) of physical address space:
          </p>

          <div className="p-3.5 bg-neutral-950 rounded-md border border-neutral-800 font-mono text-xs text-center space-y-2">
            <div className="text-amber-300 font-semibold text-sm">
              Physical Address = (Segment × 16) + Offset
            </div>
            <div className="text-[11px] text-neutral-400">
              Equivalent to: <code className="text-emerald-400">(Segment &lt;&lt; 4) + Offset</code>
            </div>
          </div>

          <div className="space-y-2 text-xs font-mono">
            <span className="text-neutral-400 block font-sans">
              Concrete Example: Accessing Mode 13h VRAM:
            </span>
            <div className="p-2.5 bg-neutral-950 rounded border border-neutral-800/80 space-y-1 text-[11px]">
              <div className="flex justify-between">
                <span className="text-neutral-400">Segment (ES):</span>
                <span className="text-amber-300">0xA000h</span>
              </div>
              <div className="flex justify-between">
                <span className="text-neutral-400">Offset (DI):</span>
                <span className="text-amber-300">0x2350h (Pixel at X:80, Y:28)</span>
              </div>
              <div className="flex justify-between border-t border-neutral-800 pt-1 text-emerald-400 font-bold">
                <span>Physical Memory Address:</span>
                <span>(0xA0000h) + 0x2350h = 0xA2350h</span>
              </div>
            </div>
          </div>
        </div>

        {/* 1MB DOS Memory Map */}
        <div className="p-5 bg-neutral-900 border border-neutral-800 rounded-lg space-y-4">
          <div className="flex items-center gap-2 border-b border-neutral-800 pb-3">
            <HardDrive size={16} className="text-emerald-400" />
            <span className="text-xs font-semibold text-neutral-200 tracking-wide font-mono">
              MS-DOS 1 MB PHYSICAL MEMORY LAYOUT
            </span>
          </div>

          {/* Graphical memory blocks */}
          <div className="space-y-1.5 font-mono text-xs">
            {/* BIOS ROM */}
            <div className="p-2 bg-neutral-950 rounded border border-neutral-800 flex items-center justify-between">
              <div>
                <span className="text-neutral-200 font-semibold block text-[11px]">
                  Motherboard BIOS ROM
                </span>
                <span className="text-[10px] text-neutral-500">
                  F0000h – FFFFFh (64 KB)
                </span>
              </div>
              <span className="text-[10px] text-neutral-400 px-2 py-0.5 rounded bg-neutral-900 border border-neutral-800">
                System Firmware
              </span>
            </div>

            {/* Video RAM (A0000h) */}
            <div className="p-2.5 bg-amber-500/10 rounded border border-amber-500/40 flex items-center justify-between">
              <div>
                <span className="text-amber-300 font-bold block text-[11px]">
                  ★ VGA Mode 13h Linear Framebuffer
                </span>
                <span className="text-[10px] text-amber-200/70 font-mono">
                  A0000h – AFFFFh (64 KB · ES:0000h)
                </span>
              </div>
              <span className="text-[10px] text-amber-300 font-bold px-2 py-0.5 rounded bg-amber-400/20 border border-amber-400/40">
                320×200 8-Bit Target
              </span>
            </div>

            {/* Text Mode Video RAM */}
            <div className="p-2 bg-neutral-950 rounded border border-neutral-800 flex items-center justify-between">
              <div>
                <span className="text-neutral-300 block text-[11px]">
                  CGA/MDA Text Mode Video RAM
                </span>
                <span className="text-[10px] text-neutral-500">
                  B8000h – BFFFFh (32 KB)
                </span>
              </div>
              <span className="text-[10px] text-neutral-400 px-2 py-0.5 rounded bg-neutral-900 border border-neutral-800">
                80×25 Text (Mode 03h)
              </span>
            </div>

            {/* Conventional Memory (640KB) */}
            <div className="p-2.5 bg-neutral-950 rounded border border-neutral-800 flex items-center justify-between">
              <div>
                <span className="text-emerald-400 font-semibold block text-[11px]">
                  Conventional Base RAM (640 KB)
                </span>
                <span className="text-[10px] text-neutral-500">
                  00000h – 9FFFFh (DOS Kernel, Drivers, MZ Program)
                </span>
              </div>
              <span className="text-[10px] text-emerald-400 px-2 py-0.5 rounded bg-emerald-500/10 border border-emerald-500/30">
                Executable Code &amp; Stack
              </span>
            </div>

            {/* Interrupt Vector Table */}
            <div className="p-2 bg-neutral-950 rounded border border-neutral-800 flex items-center justify-between">
              <div>
                <span className="text-neutral-400 block text-[11px]">
                  Interrupt Vector Table (IVT) &amp; BDA
                </span>
                <span className="text-[10px] text-neutral-500">
                  00000h – 004FFh (256 vectors of 4 bytes)
                </span>
              </div>
              <span className="text-[10px] text-neutral-500">
                INT 10h, INT 21h
              </span>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
